name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches: [ master,main ]
  pull_request:
    branches: [ master,main ]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build robot code
        run: ./gradlew build
  run-spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2025-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Runs a single command using the runners shell
    - name: Check that code is formatted correctly
      run: ./gradlew spotlessCheck